---
title: "NCRestructure"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sqldf)
library(dplyr)
```

```{r Initialize rbinding base table}
file_names <- list.files(path="C:/Users/ericj/metabolite_files/metabolite_tsvs/")
print(length(file_names))
base <- read.table(sprintf("C:/Users/ericj/metabolite_files/metabolite_tsvs/%s", file_names[1]), sep="\t", header=TRUE, fill=TRUE, quote="\"")[c(1:5, 19)]
base
```

```{r rbind all subsequent files}
i = 0
for (file in file_names[2:length(file_names)]){
  
  if (i %% 100 == 0){
    print(i)
  }
  
  binder <- read.table(sprintf("C:/Users/ericj/metabolite_files/metabolite_tsvs/%s", file), sep="\t", header=TRUE, fill=TRUE, quote="\"")[c(1:5, 19)]
  base <- rbind(base, binder)
  i = i + 1
}

df <- data.frame(base)

# Rename columns without period incompatibilities
colnames(df) <- c("INPUT", "OUTPUT", "CONTROLLER", "EVENT_ID", "EVENT_LABEL", "SEEN_IN")

# Remove anomalous rows
df <- sqldf("SELECT * FROM df WHERE SEEN_IN != ''")

df
```

```{r}
unique_papers <- unique(df$SEEN_IN)
(length(unique_papers))
```

```{r Unlabelled dataframe for NONE Controllers}
all_df <- data.frame()

for (paper in unique_papers[1:1000]){
  # Subset of individual paper
  pap_sub <- sqldf(sprintf("SELECT * FROM df WHERE SEEN_IN ='%s'", paper))
  
  # Subset of subset of paper: wherever controller is NONE
  eId_sub <- sqldf("SELECT INPUT, EVENT_ID, EVENT_LABEL FROM pap_sub WHERE CONTROLLER = 'NONE'")
  
  # Inputs as events are joined together
  in_id_shared <- inner_join(pap_sub, eId_sub, by=c("INPUT" = "EVENT_ID"))
  in_id_shared$EVENT_LABEL.x <- paste(in_id_shared$EVENT_LABEL.x, in_id_shared$EVENT_LABEL.y)
  relevant <- in_id_shared[c(1, 2, 3, 4, 5, 6)]
  colnames(relevant)[5] <- "EVENT_LABEL"
  
  all_df <- rbind(all_df, relevant)
}

all_df
```

```{r}
none_counted_df <- sqldf("SELECT INPUT, OUTPUT, CONTROLLER, EVENT_LABEL, COUNT(*) AS COUNTER, SEEN_IN FROM all_df GROUP BY OUTPUT, CONTROLLER, EVENT_LABEL ORDER BY COUNTER DESC")

none_counted_df
```
```{r}
write.csv(none_counted_df, file="C:/Users/ericj/metabolite_files/GephiVizFiles/NCCount_df.csv", row.names=FALSE)
```