---
title: "TSVRestructure"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sqldf)
```

```{r Initialize rbinding base table}
file_names <- list.files(path="C:/Users/ericj/metabolite_files/feb_chebi_tsvs/")
print(length(file_names))
base <- read.table(sprintf("C:/Users/ericj/metabolite_files/feb_chebi_tsvs/%s", file_names[1]), sep="\t", header=TRUE, fill=TRUE, quote="\"")[c(1:5, 19)]
base
```

```{r rbind all subsequent files}
i = 0
for (file in file_names){
  
  if (i %% 100 == 0){
    print(i)
  }
  
  binder <- read.table(sprintf("C:/Users/ericj/metabolite_files/feb_chebi_tsvs/%s", file), sep="\t", header=TRUE, fill=TRUE, quote="\"")[c(1:5, 19)]
  base <- rbind(base, binder)
  i = i + 1
}

df <- data.frame(base)

# Rename columns without period incompatibilities
colnames(df) <- c("INPUT", "OUTPUT", "CONTROLLER", "EVENT_ID", "EVENT_LABEL", "SEEN_IN")

df
```

```{r Find Unique Inputs}
# Number of unique pairs
sqldf("SELECT COUNT(*) from (SELECT distinct INPUT,CONTROLLER FROM df)")

# Selecting INPUT, CONTROLLER unique pairs
sqldf("SELECT INPUT, CONTROLLER, COUNT(*) AS COUNTER FROM df GROUP BY INPUT, CONTROLLER ORDER BY COUNTER DESC")

# Selecting OUTPUT, CONTROLLER unique pairs
sqldf("SELECT OUTPUT, CONTROLLER, COUNT(*) AS COUNTER FROM df GROUP BY OUTPUT, CONTROLLER ORDER BY COUNTER DESC")
```

```{r Only Pos Neg Activations}
# Here, all "NONE" Controllers are omitted. So, transcription, sumoylation, etc. are not in this dataframe.
pos_neg_counted_df <- sqldf("SELECT INPUT, OUTPUT, CONTROLLER, EVENT_LABEL, COUNT(*) AS COUNTER, SEEN_IN FROM df WHERE CONTROLLER!='NONE' GROUP BY OUTPUT, CONTROLLER, EVENT_LABEL ORDER BY COUNTER DESC")

pos_neg_counted_df
```

```{r Only Amount and Regulation labels}
# Finding AMOUNT and REGULATION
amt_reg_df <- sqldf("SELECT INPUT, OUTPUT, CONTROLLER, EVENT_LABEL, SEEN_IN, COUNT(*) AS COUNTER FROM df WHERE EVENT_LABEL = 'Amount' OR EVENT_LABEL = 'Regulation (Positive)' OR EVENT_LABEL = 'Regulation (Negative)' GROUP BY OUTPUT, CONTROLLER, EVENT_LABEL, SEEN_IN ORDER BY COUNTER DESC")
amt_reg_df
```

```{r Only ChEBI and no EventID INPUTs}
chebi_df <- sqldf("SELECT * FROM pos_neg_counted_df WHERE INPUT LIKE '%CHEBI%' AND CONTROLLER LIKE '%CHEBI%'")
chebi_df
```

```{r}
test1 <- sqldf("SELECT * FROM chebi_df WHERE INPUT='ROS::chebi:CHEBI:26523.a' AND CONTROLLER='vitamin D::chebi:CHEBI:27300'")
test2 <- sqldf("SELECT * FROM chebi_df WHERE INPUT='ROS::chebi:CHEBI:26523' AND CONTROLLER='vitamin D::chebi:CHEBI:27300'")
test1
test2
```



```{r Writer's Block}
# All Pos/Neg Activation event pairs
write.csv(pos_neg_counted_df, file = "C:/Users/ericj/metabolite_files/GephiVizFiles/pos_neg_counted_df.csv", row.names=FALSE)

# All Amount, Pos/Neg Regulation event pairs
write.csv(amt_reg_df, file="C:/Users/ericj/metabolite_files/GephiVizFiles/amt_reg_df.csv", row.names=FALSE)

# Only ChEBI Pos/Neg Activations
write.csv(chebi_df, file="C:/Users/ericj/metabolite_files/GephiVizFiles/chebi_pairs.csv", row.names=FALSE)
```